//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Chantier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chantier()
        {
            this.reclamations = new HashSet<reclamation>();
        }
    
        [DisplayName("Id Chantier")]
        [DataType(DataType.Text)]
        public int IdChantier { get; set; }
        [DisplayName("Nom de Chantier")]
        [DataType(DataType.Text)]
        public string NomChantier { get; set; }
        [DisplayName("Adresse Chantier")]
        [DataType(DataType.MultilineText)]
        public string AdresseChantier { get; set; }
        [DisplayName("Date de debut")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateDebChantier { get; set; }
        [DisplayName("Date fin")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateFinProj { get; set; }
        [DisplayName("Etat")]
        [DataType(DataType.Text)]
        public string statut { get; set; }
        [DisplayName("Chef de Chantier")]
        [DataType(DataType.Text)]
        public string ChefProj { get; set; }
        [DisplayName("Client")]
        [DataType(DataType.Text)]
        public Nullable<int> idClient { get; set; }
        [DisplayName("Points Ajouté")]
        public Nullable<int> pointsA { get; set; }
       
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reclamation> reclamations { get; set; }
    }
}
