//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Chantier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chantier()
        {
            this.reclamations = new HashSet<reclamation>();
        }
    
        [Key]
        public int IdChantier { get; set; }
        public string NomChantier { get; set; }
        public string AdresseChantier { get; set; }
        public System.DateTime DateDebChantier { get; set; }
        public Nullable<System.DateTime> DateFinProj { get; set; }
        public string statut { get; set; }
        public string ChefProj { get; set; }
        public Nullable<int> IdClient { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reclamation> reclamations { get; set; }
    }
}
