//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Congee
    {
        [DisplayName("Id Congée")]
        public int idConge { get; set; }
        [DisplayName("Employé")]
        public string IdEmp { get; set; }

        private int DataType(DataType text)
        {
            throw new NotImplementedException();
        }

        [DisplayName("Date de début")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        public System.DateTime StartDate { get; set; }

        [DisplayName("Date fin")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        public System.DateTime EndDate { get; set; }
        [DisplayName("Raison")]
        public string Reason { get; set; }
        [DisplayName("Statut")]
        public string Status { get; set; }
        [DisplayName("Employé")]
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
