//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DemangdeAug
    {
        [DisplayName("Identification")]
        public int idDemande { get; set; }
        [DisplayName("Employé")]
        public string IdEmp { get; set; }
        [DisplayName("Etat")]
        public string etat { get; set; }
        [DisplayName("Montant d'augementation")]

        public Nullable<decimal> MontantAug { get; set; }
        [DisplayName("Date de la demande")]

        public Nullable<System.DateTime> DateDemande { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
