//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DemangdeAug
    {
        [Key]

        public int IdDemande { get; set; }
        public string IdEmp { get; set; }
        public Nullable<bool> etat { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
