//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTable()
        {
            this.Congees = new HashSet<Congee>();
            this.DemangdeAugS = new HashSet<DemangdeAug>();
            this.UserTables = new HashSet<UserTable>();
            this.Chantiers = new HashSet<Chantier>();
        }
        [DisplayName("Identification")]
        public string IdEmp { get; set; }
        [DisplayName("Prenom")]
        [DataType(DataType.Text)]
        public string PrenomEmp { get; set; }
        [DisplayName("Nom")]
        [DataType(DataType.Text)]
        public string NomEmp { get; set; }
        [DisplayName("Email")]
        [DataType(DataType.EmailAddress)]
        public string MailEmp { get; set; }

        [DisplayName("Telephone")]
        [DataType(DataType.PhoneNumber)]
        public string TelEmp { get; set; }
        [DisplayName("Adresse")]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        [DisplayName("Date de naissance")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateNEmp { get; set; }
        [DisplayName("Sexe")]
        public string SexeEmp { get; set; }
        [DisplayName("Date de Recrutement")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateRecEmp { get; set; }
        [DisplayName("Département")]
        public Nullable<int> idDepartement { get; set; }
        [DisplayName("Grade")]
        [DataType(DataType.Text)]
        public string PosteEmp { get; set; }
        [DisplayName("Salaire")]
        public decimal SalaireEmp { get; set; }
        [DisplayName("Points")]
        public int pointsEmp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congee> Congees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemangdeAug> DemangdeAugS { get; set; }
        public virtual Depatement Depatement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTable> UserTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chantier> Chantiers { get; set; }
    }
}
