//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTable()
        {
            this.Congees = new HashSet<Congee>();
            this.DemangdeAugS = new HashSet<DemangdeAug>();
            this.UserTables = new HashSet<UserTable>();
            this.Chantiers = new HashSet<Chantier>();
        }
    
        public string IdEmp { get; set; }
        public string PrenomEmp { get; set; }
        public string NomEmp { get; set; }
        public string MailEmp { get; set; }
        public string TelEmp { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateNEmp { get; set; }
        public string SexeEmp { get; set; }
        public Nullable<System.DateTime> DateRecEmp { get; set; }
        public Nullable<int> idDepartement { get; set; }
        public string PosteEmp { get; set; }
        public decimal SalaireEmp { get; set; }
        public int pointsEmp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congee> Congees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DemangdeAug> DemangdeAugS { get; set; }
        public virtual Depatement Depatement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTable> UserTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chantier> Chantiers { get; set; }
    }
}
