//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTable
    {
        [Key]
        public string IdEmp { get; set; }
        public string Pseudo { get; set; }
        public string password { get; set; }
        public bool Admin { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
