//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserClient
    {
        [DisplayName("Pseudo")]
        public string pseudo { get; set; }
        [DisplayName("Mot de passe")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("Identification Client")]
        public Nullable<int> idClient { get; set; }
        [DisplayName("Client")]
        public virtual Client Client { get; set; }
    }
}
