//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_de_fin_de_formation
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserClient
    {
        public string pseudo { get; set; }
        public string password { get; set; }
        public Nullable<int> idClient { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
